import Link from "next/link";

export const metadata = {
  title: "Privacy Policy — PropValue",
};

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-stone-50">
      <nav className="flex items-center justify-between px-6 py-5 max-w-3xl mx-auto w-full">
        <Link href="/" className="font-display text-xl font-semibold tracking-tight text-ink">
          Prop<span className="text-gold-400">Value</span>
        </Link>
        <Link href="/" className="text-sm text-ink-muted hover:text-ink transition-colors">
          Back home
        </Link>
      </nav>

      <article className="max-w-3xl mx-auto px-6 pb-24 pt-4">
        <p className="font-mono text-xs uppercase tracking-widest text-gold-500 mb-3">Legal</p>
        <h1 className="font-display text-4xl md:text-5xl tracking-tight text-ink mb-2">Privacy Policy</h1>
        <p className="text-sm text-ink-faint mb-12">Last updated: 4 July 2026</p>

        <Section title="">
          <P>
            This policy explains what personal information PropValue collects, why we collect it,
            and what you can do about it. We&apos;ve written it in plain English rather than legal
            jargon — if anything is unclear, contact us using the details at the bottom of this page.
          </P>
        </Section>

        <Section title="1. Who we are">
          <P>
            PropValue is operated by <Fill>19 Sourcing Ltd</Fill>, a company registered in England
            and Wales under company number <Fill>17306899</Fill>, with its registered office
            at <Fill>124 City Road, London, England, EC1V 2NX</Fill>.
          </P>
          <P>
            For the purposes of UK data protection law, we are the &ldquo;data controller&rdquo; of the
            personal information described in this policy.
          </P>
        </Section>

        <Section title="2. What information we collect">
          <H3>Information you give us directly</H3>
          <UL>
            <LI><B>Account details:</B> when you sign in, we (via our authentication provider, Clerk) collect your name and email address, and if you sign in with Google, basic profile information from your Google account.</LI>
            <LI><B>Property searches:</B> the addresses and postcodes you search, and any property details you enter (such as bedrooms, bathrooms, property type, tenure, or condition).</LI>
          </UL>
          <H3>Information generated by using the service</H3>
          <UL>
            <LI><B>Valuation history:</B> every valuation report you run is saved to your account so you can view it again later.</LI>
            <LI><B>Generated reports:</B> the PDF reports you download are generated from your valuation data.</LI>
          </UL>
          <H3>Information collected automatically</H3>
          <UL>
            <LI><B>Technical data:</B> your IP address, browser type, device information, and session activity, collected automatically by our authentication provider (Clerk) and hosting infrastructure for security and to keep you signed in.</LI>
            <LI><B>Cookies:</B> we use cookies set by our authentication provider to keep you logged in between visits. We do not currently use cookies for advertising or analytics tracking. See Section 6 for more detail.</LI>
          </UL>
          <P>We do <B>not</B> ask for or store payment card details, since PropValue does not currently process payments.</P>
        </Section>

        <Section title="3. How we use your information, and our legal basis for doing so">
          <Table
            head={["What we use it for", "Our legal basis"]}
            rows={[
              ["Creating and maintaining your account", "Necessary to perform our contract with you"],
              ["Running property valuations and generating reports", "Necessary to perform our contract with you"],
              ["Saving your valuation history so you can access it later", "Necessary to perform our contract with you"],
              ["Keeping the service secure and preventing abuse", "Our legitimate interest in protecting the service and our users"],
              ["Improving and maintaining the platform", "Our legitimate interest in running and improving our business"],
              ["Contacting you about your account (e.g. security notices)", "Necessary to perform our contract with you"],
            ]}
          />
          <P>
            We do not use your personal information for automated decision-making that has a legal or
            similarly significant effect on you, and we do not sell your personal information to third parties.
          </P>
        </Section>

        <Section title="4. Who we share your information with">
          <P>To provide the service, certain information is shared with carefully chosen third-party providers, each acting under their own privacy obligations:</P>
          <UL>
            <LI><B>Clerk</B> (authentication) — processes your name, email address, and sign-in activity to manage your account and keep you securely logged in.</LI>
            <LI><B>PropertyData, the EPC Register, and Homedata</B> — when you search a property, the address or postcode you enter is sent to these UK property-data providers to retrieve comparable sales, EPC ratings, and property characteristics. These providers do not receive your name or account details — only the address being valued.</LI>
            <LI><B>Railway</B> — hosts our database, which stores your account details and valuation history securely.</LI>
            <LI><B>Vercel</B> — hosts the website you&apos;re using right now.</LI>
          </UL>
          <P>We do not share your personal information with third parties for their own marketing purposes, and we do not sell personal information.</P>
        </Section>

        <Section title="5. International data transfers">
          <P>
            Some of the providers listed above (including Clerk, Railway, and Vercel) may store or
            process data outside the UK, including in the United States. Where this happens, we rely
            on legally recognised safeguards — such as Standard Contractual Clauses or the provider&apos;s
            participation in a recognised data-transfer framework — to ensure your information receives
            an equivalent standard of protection to that required under UK data protection law.
          </P>
        </Section>

        <Section title="6. Cookies">
          <P>
            We use a small number of strictly necessary cookies, set by Clerk, to keep you signed in
            securely between visits. These are essential for the service to function and cannot be
            switched off without losing the ability to stay logged in.
          </P>
          <P>
            We do not currently use cookies for advertising, analytics, or cross-site tracking. If this
            changes in the future, we will update this policy and, where required by law, ask for your
            consent first.
          </P>
        </Section>

        <Section title="7. How long we keep your information">
          <P>
            We keep your account information and valuation history for as long as your account remains
            active. If you delete your account, we will delete your personal information within{" "}
            <Fill>[TIMEFRAME, e.g. &ldquo;30 days&rdquo;]</Fill>, except where we&apos;re required to keep certain
            records for longer to comply with a legal obligation.
          </P>
        </Section>

        <Section title="8. Children">
          <P>
            PropValue is not intended for use by anyone under the age of 18, and we do not knowingly
            collect personal information from children. If you believe a child has provided us with
            personal information, please contact us and we will delete it.
          </P>
        </Section>

        <Section title="9. Your rights">
          <P>Under UK data protection law, you have the right to:</P>
          <UL>
            <LI><B>Access</B> the personal information we hold about you</LI>
            <LI><B>Correct</B> inaccurate or incomplete information</LI>
            <LI><B>Erase</B> your personal information (the &ldquo;right to be forgotten&rdquo;)</LI>
            <LI><B>Restrict</B> how we use your information</LI>
            <LI><B>Object</B> to certain uses of your information</LI>
            <LI><B>Receive a copy</B> of your information in a portable format (&ldquo;data portability&rdquo;)</LI>
          </UL>
          <P>To exercise any of these rights, contact us using the details below. We&apos;ll respond within one month, as required by law.</P>
          <P>
            If you&apos;re unhappy with how we&apos;ve handled your information, you also have the right to
            complain to the UK&apos;s data protection regulator, the <B>Information Commissioner&apos;s Office
            (ICO)</B>, at{" "}
            <a href="https://ico.org.uk" className="text-ink underline hover:text-gold-500">ico.org.uk</a>{" "}
            or on 0303 123 1113. We&apos;d appreciate the chance to resolve any concerns directly first, but
            you&apos;re not required to contact us before complaining to the ICO.
          </P>
        </Section>

        <Section title="10. How we protect your information">
          <P>
            We use industry-standard security measures, including encrypted connections (HTTPS) and
            secure, access-controlled hosting, to protect your personal information against
            unauthorised access, loss, or misuse. No method of transmission or storage is 100% secure,
            but we take reasonable steps to protect your data appropriately.
          </P>
        </Section>

        <Section title="11. Changes to this policy">
          <P>
            We may update this policy from time to time, for example if we add new features or change
            service providers. If we make significant changes, we&apos;ll let you know — for example, by
            email or a notice on the site — before the changes take effect.
          </P>
        </Section>

        <Section title="12. Contact us">
          <P>If you have any questions about this policy or how we handle your personal information, contact us at:</P>
          <p className="text-ink font-medium">
            <Fill>info@19sourcing.com</Fill><br />
            <Fill>19 Sourcing Ltd</Fill><br />
            <Fill>124 City Road, London, England, EC1V 2NX</Fill>
          </p>
        </Section>
      </article>

      <footer className="border-t border-stone-100 py-8 px-6">
        <div className="max-w-3xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4 text-xs text-ink-faint">
          <span>© 2026 PropValue. Not a RICS-compliant valuation.</span>
          <div className="flex gap-6">
            <Link href="/privacy" className="hover:text-ink transition-colors">Privacy</Link>
            <Link href="/terms" className="hover:text-ink transition-colors">Terms</Link>
          </div>
        </div>
      </footer>
    </main>
  );
}

// ── Shared typographic helpers ─────────────────────────────────
function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      {title && <h2 className="font-display text-xl text-ink mb-4 tracking-tight">{title}</h2>}
      {children}
    </section>
  );
}
function H3({ children }: { children: React.ReactNode }) {
  return <h3 className="font-display text-base text-ink mt-5 mb-2">{children}</h3>;
}
function P({ children }: { children: React.ReactNode }) {
  return <p className="text-[15px] leading-relaxed text-ink-muted mb-4">{children}</p>;
}
function B({ children }: { children: React.ReactNode }) {
  return <strong className="text-ink font-semibold">{children}</strong>;
}
function Fill({ children }: { children: React.ReactNode }) {
  return <span className="bg-gold-300/30 text-gold-500 px-1.5 py-0.5 rounded font-mono text-[13px]">{children}</span>;
}
function UL({ children }: { children: React.ReactNode }) {
  return <ul className="list-disc pl-5 space-y-2 mb-4 text-[15px] leading-relaxed text-ink-muted">{children}</ul>;
}
function LI({ children }: { children: React.ReactNode }) {
  return <li>{children}</li>;
}
function Table({ head, rows }: { head: string[]; rows: string[][] }) {
  return (
    <div className="overflow-x-auto mb-4 rounded-xl border border-stone-200">
      <table className="w-full text-sm">
        <thead>
          <tr className="bg-stone-100">
            {head.map((h) => (
              <th key={h} className="text-left font-mono text-xs uppercase tracking-wider text-ink-muted px-4 py-3">{h}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((row, i) => (
            <tr key={i} className="border-t border-stone-100">
              {row.map((cell, j) => (
                <td key={j} className="px-4 py-3 text-ink-muted align-top">{cell}</td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
