import Link from "next/link";

export const metadata = {
  title: "Terms of Service — PropVal",
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-stone-50">
      <nav className="flex items-center justify-between px-6 py-5 max-w-3xl mx-auto w-full">
        <Link href="/" className="font-display text-xl font-semibold tracking-tight text-ink">
          Prop<span className="text-gold-400">Val</span>
        </Link>
        <Link href="/" className="text-sm text-ink-muted hover:text-ink transition-colors">
          Back home
        </Link>
      </nav>

      <article className="max-w-3xl mx-auto px-6 pb-24 pt-4">
        <p className="font-mono text-xs uppercase tracking-widest text-gold-500 mb-3">Legal</p>
        <h1 className="font-display text-4xl md:text-5xl tracking-tight text-ink mb-2">Terms of Service</h1>
        <p className="text-sm text-ink-faint mb-12">Last updated: 4 July 2026</p>

        <Section title="">
          <P>Please read these terms carefully before using PropVal. By creating an account or using the service, you agree to be bound by them.</P>
        </Section>

        <Section title="1. Who we are">
          <P>
            PropVal is operated by <Fill>19 Sourcing Ltd</Fill> (&ldquo;PropVal&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;,
            &ldquo;our&rdquo;), a company registered in England and Wales under company number{" "}
            <Fill>17306899</Fill>, with its registered office at <Fill>124 City Road, London, England, EC1V 2NX</Fill>.
          </P>
        </Section>

        <Section title="2. What PropVal does">
          <P>
            PropVal provides instant, automated estimates of UK residential property values
            (&ldquo;Valuations&rdquo;), generated using a computer model that combines publicly available
            and licensed data, including HM Land Registry sold-price data, EPC certificate data, and
            third-party property data providers.
          </P>
        </Section>

        <Section title="3. Important: the nature of our Valuations">
          <div className="rounded-xl border border-gold-300/50 bg-gold-300/10 px-5 py-4 mb-4">
            <p className="text-[13px] font-mono uppercase tracking-wider text-gold-500 mb-2">Please read this section carefully — it&apos;s the most important part of these terms.</p>
          </div>
          <UL>
            <LI>Valuations produced by PropVal are <B>automated estimates only</B>. They are generated by a computer model, without any physical inspection of the property, its condition, or any legal documents relating to it.</LI>
            <LI>PropVal is <B>not a RICS-regulated valuation</B> and does not meet the standards required for a formal &ldquo;Red Book&rdquo; valuation under Royal Institution of Chartered Surveyors guidelines.</LI>
            <LI>Valuations <B>must not be relied upon</B> as the sole basis for any financial, legal, lending, insurance, or property-purchase decision. If you are buying, selling, re-mortgaging, or otherwise making a financial decision involving a property, you should obtain a professional valuation from a RICS-qualified surveyor and/or independent legal and financial advice.</LI>
            <LI>We do not guarantee the accuracy, completeness, or currency of any Valuation, comparable sales data, EPC information, or other data shown on the platform. Data is sourced from third parties and may be incomplete, outdated, or contain errors that are outside our control.</LI>
            <LI>To the fullest extent permitted by law, PropVal accepts no liability for any loss or damage arising from reliance on a Valuation or any other information provided through the service.</LI>
          </UL>
        </Section>

        <Section title="4. Eligibility and your account">
          <UL>
            <LI>You must be at least 18 years old to create an account or use PropVal.</LI>
            <LI>You&apos;re responsible for keeping your login credentials secure and for all activity that takes place under your account.</LI>
            <LI>You agree to provide accurate information when creating your account and when entering property details.</LI>
            <LI>You&apos;re responsible for notifying us promptly if you become aware of any unauthorised use of your account.</LI>
          </UL>
        </Section>

        <Section title="5. Acceptable use">
          <P>When using PropVal, you agree not to:</P>
          <UL>
            <LI>Use automated tools, scripts, or bots to scrape, harvest, or systematically extract data from the platform</LI>
            <LI>Attempt to reverse-engineer, copy, or resell PropVal&apos;s valuation methodology or underlying data as a competing product</LI>
            <LI>Use the service for any unlawful purpose, or in a way that could damage, disable, or impair the platform</LI>
            <LI>Attempt to gain unauthorised access to any part of the service, other users&apos; accounts, or our underlying systems</LI>
            <LI>Use the service to generate Valuations at a scale or in a manner inconsistent with normal individual use, without our prior written agreement</LI>
          </UL>
          <P>We reserve the right to suspend or terminate accounts that breach these terms.</P>
        </Section>

        <Section title="6. Intellectual property">
          <P>
            PropVal, its branding, the design and layout of generated reports, and the underlying
            software and valuation methodology are owned by us or our licensors and protected by
            copyright and other intellectual property laws. You may download and use Valuation
            reports for your own personal or business reference, but you may not republish, resell,
            or redistribute them as a standalone commercial product without our permission.
          </P>
        </Section>

        <Section title="7. Third-party data and services">
          <P>
            PropVal relies on third-party data providers, including but not limited to HM Land
            Registry, the EPC Register, PropertyData, and Homedata. We are not responsible for the
            accuracy of data provided by these third parties, and our agreements with them may
            change, which could affect the availability or accuracy of features on PropVal from
            time to time.
          </P>
        </Section>

        <Section title="8. Limitation of liability">
          <P>To the fullest extent permitted by law:</P>
          <UL>
            <LI>PropVal is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo;, without warranties of any kind, whether express or implied.</LI>
            <LI>We do not warrant that the service will be uninterrupted, error-free, or available at all times.</LI>
            <LI>We are not liable for any indirect, incidental, special, or consequential losses, including but not limited to loss of profit, loss of opportunity, or loss arising from a property transaction entered into in reliance on a Valuation.</LI>
            <LI>Our total liability to you for any claim arising from your use of PropVal, however it arises, is limited to the greater of £100 or the total amount (if any) you have paid us in the 12 months before the claim arose.</LI>
          </UL>
          <P>
            Nothing in these terms limits or excludes our liability for death or personal injury
            caused by our negligence, fraud, or any other liability that cannot lawfully be limited
            or excluded.
          </P>
        </Section>

        <Section title="9. Termination">
          <P>
            You may stop using PropVal and delete your account at any time. We may suspend or
            terminate your access to the service if you breach these terms, or if we reasonably
            believe your use of the service poses a risk to PropVal, other users, or any third party.
          </P>
        </Section>

        <Section title="10. Changes to these terms">
          <P>
            We may update these terms from time to time, for example to reflect changes in the
            service or in the law. If we make material changes, we&apos;ll give you reasonable notice
            — for example, by email or a notice on the site — before the changes take effect.
            Continuing to use PropVal after changes take effect means you accept the updated terms.
          </P>
        </Section>

        <Section title="11. Governing law">
          <P>
            These terms are governed by the laws of England and Wales, and any disputes will be
            subject to the exclusive jurisdiction of the courts of England and Wales.
          </P>
        </Section>

        <Section title="12. Contact us">
          <P>If you have any questions about these terms, contact us at:</P>
          <p className="text-ink font-medium">
            <Fill>hello@propval.co.uk</Fill><br />
            <Fill>19 Sourcing Ltd</Fill><br />
            <Fill>124 City Road, London, England, EC1V 2NX</Fill>
          </p>
        </Section>
      </article>

      <footer className="border-t border-stone-100 py-8 px-6">
        <div className="max-w-3xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4 text-xs text-ink-faint">
          <span>© 2026 PropVal. Not a RICS-compliant valuation.</span>
          <div className="flex gap-6">
            <Link href="/privacy" className="hover:text-ink transition-colors">Privacy</Link>
            <Link href="/terms" className="hover:text-ink transition-colors">Terms</Link>
          </div>
        </div>
      </footer>
    </main>
  );
}

// ── Shared typographic helpers ─────────────────────────────────
function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      {title && <h2 className="font-display text-xl text-ink mb-4 tracking-tight">{title}</h2>}
      {children}
    </section>
  );
}
function P({ children }: { children: React.ReactNode }) {
  return <p className="text-[15px] leading-relaxed text-ink-muted mb-4">{children}</p>;
}
function B({ children }: { children: React.ReactNode }) {
  return <strong className="text-ink font-semibold">{children}</strong>;
}
function Fill({ children }: { children: React.ReactNode }) {
  return <span className="bg-gold-300/30 text-gold-500 px-1.5 py-0.5 rounded font-mono text-[13px]">{children}</span>;
}
function UL({ children }: { children: React.ReactNode }) {
  return <ul className="list-disc pl-5 space-y-2 mb-4 text-[15px] leading-relaxed text-ink-muted">{children}</ul>;
}
function LI({ children }: { children: React.ReactNode }) {
  return <li>{children}</li>;
}
